version: "3.7"

services:
  db:
    image: "postgres:11.5"
    container_name: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres

  profile-frontend:
    image: "profile-client:1.0.0"
    container_name: "profile-frontend"
    ports: 
      - "3000:3000"
    restart: always

  profile-backend:
    image: "profile-server:1.0.0"
    container_name: "profile-backend"
    ports: 
      - "8080:8080"
    depends_on:
      - "db"
    restart: always
